// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\CordicKernelMag_block.sv
// Created: 2024-03-28 20:55:43
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------


import envelopeModulation_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: CordicKernelMag_block
// Source Path: envelopeModulation_fixpt/HDL_CMA_core/CordicKernelMag
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CordicKernelMag_block
          (  input logic signed [23:0] xin  /* sfix24 */,
             input logic signed [23:0] yin  /* sfix24 */,
             input logic [5:0] idx  /* ufix6 */,
             output logic signed [23:0] xout  /* sfix24 */,
             output logic signed [23:0] yout  /* sfix24 */);


  logic yLessThanZero;
  logic [7:0] dynamic_shift_1;  /* uint8 */
  logic signed [23:0] yShifted;  /* sfix24 */
  logic signed [23:0] xout2;  /* sfix24 */
  logic signed [23:0] xout1;  /* sfix24 */
  logic [7:0] dynamic_shift_3;  /* uint8 */
  logic signed [23:0] xShifted;  /* sfix24 */
  logic signed [23:0] yout2;  /* sfix24 */
  logic signed [23:0] yout1;  /* sfix24 */


  assign yLessThanZero = yin < 24'sb000000000000000000000000;



  assign dynamic_shift_1 = {2'b0, idx};
  assign yShifted = yin >>> dynamic_shift_1;



  assign xout2 = xin + yShifted;



  assign xout1 = xin - yShifted;



  assign xout = (yLessThanZero == 1'b0 ? xout2 :
              xout1);



  assign dynamic_shift_3 = {2'b0, idx};
  assign xShifted = xin >>> dynamic_shift_3;



  assign yout2 = yin - xShifted;



  assign yout1 = yin + xShifted;



  assign yout = (yLessThanZero == 1'b0 ? yout2 :
              yout1);



endmodule  // CordicKernelMag_block

