// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\envelopeModulation_fixpt_pkg.sv
// Created: 2024-03-28 20:55:44
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------



package envelopeModulation_fixpt_pkg;
  typedef  logic signed [7:0] vector_of_signed_logic_8;

  typedef  logic signed [25:0] vector_of_signed_logic_26;

  typedef  logic  [4:0] vector_of_unsigned_logic_5;

  typedef  logic signed [12:0] vector_of_signed_logic_13;

  typedef  logic signed [14:0] vector_of_signed_logic_15;
  typedef  logic signed [16:0] vector_of_signed_logic_17;
  typedef  logic signed [18:0] vector_of_signed_logic_19;
  typedef  logic signed [20:0] vector_of_signed_logic_21;

  typedef  logic signed [31:0] vector_of_signed_logic_32;
  typedef  logic  [7:0] vector_of_unsigned_logic_8;
endpackage: envelopeModulation_fixpt_pkg

