onerror {quit -f}
onbreak {quit -f}
vlib work
vlog  envelopeModulation_fixpt_pkg.sv
vlog  SimpleDualPortRAM_generic.sv
vlog  SDFCommutator1.sv
vlog  RADIX22FFT_SDF1_1.sv
vlog  RADIX22FFT_CTRL1_1.sv
vlog  SDFCommutator2.sv
vlog  RADIX22FFT_SDF2_2.sv
vlog  RADIX22FFT_CTRL1_2.sv
vlog  TWDLROM_3_1.sv
vlog  Complex4Multiply.sv
vlog  SDFCommutator3.sv
vlog  RADIX22FFT_SDF1_3.sv
vlog  RADIX22FFT_CTRL1_3.sv
vlog  SDFCommutator4.sv
vlog  RADIX22FFT_SDF2_4.sv
vlog  RADIX22FFT_CTRL1_4.sv
vlog  TWDLROM_5_1.sv
vlog  Complex4Multiply_block.sv
vlog  SDFCommutator5.sv
vlog  RADIX22FFT_SDF1_5.sv
vlog  RADIX22FFT_CTRL1_5.sv
vlog  SDFCommutator6.sv
vlog  RADIX22FFT_SDF2_6.sv
vlog  RADIX22FFT_CTRL1_6.sv
vlog  TWDLROM_7_1.sv
vlog  Complex4Multiply_block1.sv
vlog  SDFCommutator7.sv
vlog  RADIX22FFT_SDF1_7.sv
vlog  RADIX22FFT_CTRL1_7.sv
vlog  SDFCommutator8.sv
vlog  RADIX22FFT_SDF2_8.sv
vlog  RADIX22FFT_CTRL1_8.sv
vlog  TWDLROM_9_1.sv
vlog  Complex4Multiply_block2.sv
vlog  SDFCommutator9.sv
vlog  RADIX22FFT_SDF1_9.sv
vlog  RADIX22FFT_CTRL1_9.sv
vlog  SDFCommutator10.sv
vlog  RADIX22FFT_SDF2_10.sv
vlog  RADIX22FFT_CTRL1_10.sv
vlog  dsphdl_IFFT.sv
vlog  Quadrant_Mapper.sv
vlog  CordicKernelMag.sv
vlog  Quadrant_Correction.sv
vlog  HDL_CMA_core.sv
vlog  Quadrant_Mapper_block.sv
vlog  CordicKernelMag_block.sv
vlog  HDL_CMA_core_block.sv
vlog  SDFCommutator1_block.sv
vlog  RADIX22FFT_SDF1_1_block.sv
vlog  RADIX22FFT_CTRL1_1_block.sv
vlog  SDFCommutator2_block.sv
vlog  RADIX22FFT_SDF2_2_block.sv
vlog  RADIX22FFT_CTRL1_2_block.sv
vlog  TWDLROM_3_1_block.sv
vlog  Complex4Multiply_block3.sv
vlog  SDFCommutator3_block.sv
vlog  RADIX22FFT_SDF1_3_block.sv
vlog  RADIX22FFT_CTRL1_3_block.sv
vlog  SDFCommutator4_block.sv
vlog  RADIX22FFT_SDF2_4_block.sv
vlog  RADIX22FFT_CTRL1_4_block.sv
vlog  TWDLROM_5_1_block.sv
vlog  Complex4Multiply_block4.sv
vlog  SDFCommutator5_block.sv
vlog  RADIX22FFT_SDF1_5_block.sv
vlog  RADIX22FFT_CTRL1_5_block.sv
vlog  SDFCommutator6_block.sv
vlog  RADIX22FFT_SDF2_6_block.sv
vlog  RADIX22FFT_CTRL1_6_block.sv
vlog  TWDLROM_7_1_block.sv
vlog  Complex4Multiply_block5.sv
vlog  SDFCommutator7_block.sv
vlog  RADIX22FFT_SDF1_7_block.sv
vlog  RADIX22FFT_CTRL1_7_block.sv
vlog  SDFCommutator8_block.sv
vlog  RADIX22FFT_SDF2_8_block.sv
vlog  RADIX22FFT_CTRL1_8_block.sv
vlog  TWDLROM_9_1_block.sv
vlog  Complex4Multiply_block6.sv
vlog  SDFCommutator9_block.sv
vlog  RADIX22FFT_SDF1_9_block.sv
vlog  RADIX22FFT_CTRL1_9_block.sv
vlog  SDFCommutator10_block.sv
vlog  RADIX22FFT_SDF2_10_block.sv
vlog  RADIX22FFT_CTRL1_10_block.sv
vlog  RADIX2FFT_bitNatural.sv
vlog  dsphdl_FFT.sv
vlog  SDFCommutator1_block1.sv
vlog  RADIX22FFT_SDF1_1_block1.sv
vlog  RADIX22FFT_CTRL1_1_block1.sv
vlog  SDFCommutator2_block1.sv
vlog  RADIX22FFT_SDF2_2_block1.sv
vlog  RADIX22FFT_CTRL1_2_block1.sv
vlog  TWDLROM_3_1_block1.sv
vlog  Complex4Multiply_block7.sv
vlog  SDFCommutator3_block1.sv
vlog  RADIX22FFT_SDF1_3_block1.sv
vlog  RADIX22FFT_CTRL1_3_block1.sv
vlog  SDFCommutator4_block1.sv
vlog  RADIX22FFT_SDF2_4_block1.sv
vlog  RADIX22FFT_CTRL1_4_block1.sv
vlog  TWDLROM_5_1_block1.sv
vlog  Complex4Multiply_block8.sv
vlog  SDFCommutator5_block1.sv
vlog  RADIX22FFT_SDF1_5_block1.sv
vlog  RADIX22FFT_CTRL1_5_block1.sv
vlog  SDFCommutator6_block1.sv
vlog  RADIX22FFT_SDF2_6_block1.sv
vlog  RADIX22FFT_CTRL1_6_block1.sv
vlog  TWDLROM_7_1_block1.sv
vlog  Complex4Multiply_block9.sv
vlog  SDFCommutator7_block1.sv
vlog  RADIX22FFT_SDF1_7_block1.sv
vlog  RADIX22FFT_CTRL1_7_block1.sv
vlog  SDFCommutator8_block1.sv
vlog  RADIX22FFT_SDF2_8_block1.sv
vlog  RADIX22FFT_CTRL1_8_block1.sv
vlog  TWDLROM_9_1_block1.sv
vlog  Complex4Multiply_block10.sv
vlog  SDFCommutator9_block1.sv
vlog  RADIX22FFT_SDF1_9_block1.sv
vlog  RADIX22FFT_CTRL1_9_block1.sv
vlog  SDFCommutator10_block1.sv
vlog  RADIX22FFT_SDF2_10_block1.sv
vlog  RADIX22FFT_CTRL1_10_block1.sv
vlog  RADIX2FFT_bitNatural_block.sv
vlog  dsphdl_FFT_block.sv
vlog  envelopeModulation_fixpt.sv
vlog  envelopeModulation_fixpt_tb.sv
quit -f
