// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\RADIX22FFT_SDF2_10_block1.sv
// Created: 2024-03-28 20:55:43
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------


import envelopeModulation_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF2_10_block1
// Source Path: envelopeModulation_fixpt/dsphdl.FFT/RADIX22FFT_SDF2_10
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF2_10_block1
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [21:0] dout_9_1_re  /* sfix22 */,
             input logic signed [21:0] dout_9_1_im  /* sfix22 */,
             input logic dout_9_1_vld,
             input logic rd_10_Addr,
             input logic rd_10_Enb,
             input logic proc_10_enb,
             input logic multiply_10_J,
             input logic softReset,
             output logic signed [22:0] dout_10_1_re  /* sfix23 */,
             output logic signed [22:0] dout_10_1_im  /* sfix23 */,
             output logic dout_10_1_vld,
             output logic dinXTwdl_10_1_vld);


  logic signed [22:0] din_re;  /* sfix23 */
  logic signed [22:0] din_im;  /* sfix23 */
  logic saveEnb;
  logic dinVld;
  logic signed [22:0] din_re_dly1;  /* sfix23 */
  logic signed [22:0] btfin_re;  /* sfix23 */
  logic signed [22:0] din_im_dly1;  /* sfix23 */
  logic signed [22:0] btfin_im;  /* sfix23 */
  logic mulIn_vld;
  logic procEnb_dly1;
  logic btfin_vld;
  logic x_vld;
  logic x_vld_dly;
  logic signed [22:0] x_im;  /* sfix23 */
  logic signed [22:0] x_im_dly;  /* sfix23 */
  logic signed [22:0] wrData_re;  /* sfix23 */
  logic signed [22:0] wrData_im;  /* sfix23 */
  logic wrAddr;  /* ufix1 */
  logic wrEnb;
  logic signed [22:0] twoLocationReg_0_MEM_re_0;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_im_0;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_re_1;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_im_1;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_dout_re_reg;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_dout_im_reg;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_re_0_next;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_im_0_next;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_re_1_next;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_im_1_next;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_dout_re_reg_next;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_dout_im_reg_next;  /* sfix23 */
  logic signed [22:0] x_re;  /* sfix23 */
  logic signed [22:0] x_re_dly;  /* sfix23 */
  logic Radix22ButterflyG2_procEnb_dly;
  logic Radix22ButterflyG2_procEnb_dly1;
  logic Radix22ButterflyG2_procEnb_dly2;
  logic signed [23:0] Radix22ButterflyG2_btf1_re_reg;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_btf1_im_reg;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_btf2_re_reg;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_btf2_im_reg;  /* sfix24 */
  logic signed [22:0] Radix22ButterflyG2_din_re_dly;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_din_im_dly;  /* sfix23 */
  logic Radix22ButterflyG2_din_vld_dly;
  logic signed [22:0] Radix22ButterflyG2_x_re_dly;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_x_im_dly;  /* sfix23 */
  logic Radix22ButterflyG2_x_vld_dly;
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  /* sfix23 */
  logic Radix22ButterflyG2_multiply_J_dly1;
  logic Radix22ButterflyG2_procEnb_dly_next;
  logic Radix22ButterflyG2_procEnb_dly1_next;
  logic Radix22ButterflyG2_procEnb_dly2_next;
  logic signed [23:0] Radix22ButterflyG2_btf1_re_reg_next;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_btf1_im_reg_next;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_btf2_re_reg_next;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_btf2_im_reg_next;  /* sfix24 */
  logic signed [22:0] Radix22ButterflyG2_din_re_dly_next;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_din_im_dly_next;  /* sfix23 */
  logic Radix22ButterflyG2_din_vld_dly_next;
  logic signed [22:0] Radix22ButterflyG2_x_re_dly_next;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_x_im_dly_next;  /* sfix23 */
  logic Radix22ButterflyG2_x_vld_dly_next;
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  /* sfix23 */
  logic Radix22ButterflyG2_multiply_J_dly1_next;
  logic signed [22:0] xf_re;  /* sfix23 */
  logic signed [22:0] xf_im;  /* sfix23 */
  logic xf_vld;
  logic signed [22:0] dinf_re;  /* sfix23 */
  logic signed [22:0] dinf_im;  /* sfix23 */
  logic dinf_vld;
  logic signed [22:0] btf1_re;  /* sfix23 */
  logic signed [22:0] btf1_im;  /* sfix23 */
  logic signed [22:0] btf2_re;  /* sfix23 */
  logic signed [22:0] btf2_im;  /* sfix23 */
  logic btfout_vld;
  logic signed [23:0] Radix22ButterflyG2_t_0;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_1;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_2;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_3;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_4;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_5;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_6;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_7;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_8;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_9;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_10;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_11;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_12;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_13;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_14;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG2_t_15;  /* sfix24 */


  assign din_re = {dout_9_1_re[21], dout_9_1_re};



  assign din_im = {dout_9_1_im[21], dout_9_1_im};



  assign saveEnb =  ~ proc_10_enb;



  assign dinVld = dout_9_1_vld & saveEnb;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_dly1 <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          din_re_dly1 <= din_re;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        btfin_re <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_re <= din_re_dly1;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        din_im_dly1 <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          din_im_dly1 <= din_im;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        btfin_im <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_im <= din_im_dly1;
        end
      end
    end



  assign mulIn_vld = dout_9_1_vld & proc_10_enb;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        procEnb_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          procEnb_dly1 <= mulIn_vld;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        btfin_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          btfin_vld <= procEnb_dly1;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_10_Enb;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        x_im_dly <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end



  // twoLocationReg_0
  always_ff @(posedge clk or posedge reset)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 23'sb00000000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 23'sb00000000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 23'sb00000000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 23'sb00000000000000000000000;
        twoLocationReg_0_dout_re_reg <= 23'sb00000000000000000000000;
        twoLocationReg_0_dout_im_reg <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always @(rd_10_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_10_Addr) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        x_re_dly <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always_ff @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_im,
       btfin_re, btfin_vld, dinVld, din_im, din_re, multiply_10_J, x_im_dly,
       x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_t_0 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_1 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_2 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_3 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_4 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_5 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_6 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_7 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_8 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_9 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_10 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_11 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_12 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_13 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_14 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_t_15 = 24'sb000000000000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_t_0 = {x_re_dly[22], x_re_dly};
      Radix22ButterflyG2_t_1 = {Radix22ButterflyG2_dinXTwdl_im_dly2[22], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_t_0 + Radix22ButterflyG2_t_1;
      Radix22ButterflyG2_t_2 = {x_re_dly[22], x_re_dly};
      Radix22ButterflyG2_t_3 = {Radix22ButterflyG2_dinXTwdl_im_dly2[22], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_t_2 - Radix22ButterflyG2_t_3;
      Radix22ButterflyG2_t_4 = {x_im_dly[22], x_im_dly};
      Radix22ButterflyG2_t_5 = {Radix22ButterflyG2_dinXTwdl_re_dly2[22], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_t_4 + Radix22ButterflyG2_t_5;
      Radix22ButterflyG2_t_6 = {x_im_dly[22], x_im_dly};
      Radix22ButterflyG2_t_7 = {Radix22ButterflyG2_dinXTwdl_re_dly2[22], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_t_6 - Radix22ButterflyG2_t_7;
    end
    else begin
      Radix22ButterflyG2_t_8 = {x_re_dly[22], x_re_dly};
      Radix22ButterflyG2_t_9 = {Radix22ButterflyG2_dinXTwdl_re_dly2[22], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_t_8 + Radix22ButterflyG2_t_9;
      Radix22ButterflyG2_t_10 = {x_re_dly[22], x_re_dly};
      Radix22ButterflyG2_t_11 = {Radix22ButterflyG2_dinXTwdl_re_dly2[22], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_t_10 - Radix22ButterflyG2_t_11;
      Radix22ButterflyG2_t_12 = {x_im_dly[22], x_im_dly};
      Radix22ButterflyG2_t_13 = {Radix22ButterflyG2_dinXTwdl_im_dly2[22], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_t_12 + Radix22ButterflyG2_t_13;
      Radix22ButterflyG2_t_14 = {x_im_dly[22], x_im_dly};
      Radix22ButterflyG2_t_15 = {Radix22ButterflyG2_dinXTwdl_im_dly2[22], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_t_14 - Radix22ButterflyG2_t_15;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = btfin_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = btfin_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_10_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[22:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[22:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[22:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[22:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  SDFCommutator10_block1 u_SDFCOMMUTATOR_10 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_9_1_vld(dout_9_1_vld),
                                             .xf_re(xf_re),  /* sfix23 */
                                             .xf_im(xf_im),  /* sfix23 */
                                             .xf_vld(xf_vld),
                                             .dinf_re(dinf_re),  /* sfix23 */
                                             .dinf_im(dinf_im),  /* sfix23 */
                                             .dinf_vld(dinf_vld),
                                             .btf1_re(btf1_re),  /* sfix23 */
                                             .btf1_im(btf1_im),  /* sfix23 */
                                             .btf2_re(btf2_re),  /* sfix23 */
                                             .btf2_im(btf2_im),  /* sfix23 */
                                             .btfout_vld(btfout_vld),
                                             .softReset(softReset),
                                             .wrData_re(wrData_re),  /* sfix23 */
                                             .wrData_im(wrData_im),  /* sfix23 */
                                             .wrAddr(wrAddr),  /* ufix1 */
                                             .wrEnb(wrEnb),
                                             .dout_10_1_re(dout_10_1_re),  /* sfix23 */
                                             .dout_10_1_im(dout_10_1_im),  /* sfix23 */
                                             .dout_10_1_vld(dout_10_1_vld)
                                             );

  assign dinXTwdl_10_1_vld = btfin_vld;

endmodule  // RADIX22FFT_SDF2_10_block1

