// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\RADIX22FFT_SDF1_1_block1.sv
// Created: 2024-03-28 20:55:43
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------


import envelopeModulation_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_1_block1
// Source Path: envelopeModulation_fixpt/dsphdl.FFT/RADIX22FFT_SDF1_1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_1_block1
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [12:0] din_1_1_re_dly  /* sfix13 */,
             input logic signed [12:0] din_1_1_im_dly  /* sfix13 */,
             input logic din_1_vld_dly,
             input logic [8:0] rd_1_Addr  /* ufix9 */,
             input logic rd_1_Enb,
             input logic signed [12:0] twdl_1_1_re  /* sfix13_En11 */,
             input logic signed [12:0] twdl_1_1_im  /* sfix13_En11 */,
             input logic twdl_1_1_vld,
             input logic proc_1_enb,
             input logic softReset,
             output logic signed [13:0] dout_1_1_re  /* sfix14 */,
             output logic signed [13:0] dout_1_1_im  /* sfix14 */,
             output logic dout_1_1_vld,
             output logic dinXTwdl_1_1_vld);


  logic signed [13:0] din_re;  /* sfix14 */
  logic signed [13:0] dinXTwdl_re;  /* sfix14 */
  logic signed [13:0] din_im;  /* sfix14 */
  logic signed [13:0] dinXTwdl_im;  /* sfix14 */
  logic dinXTwdl_1_1_vld_1;
  logic x_vld;
  logic signed [13:0] wrData_im;  /* sfix14 */
  logic [8:0] wrAddr;  /* ufix9 */
  logic wrEnb;
  logic signed [13:0] x_im;  /* sfix14 */
  logic signed [13:0] wrData_re;  /* sfix14 */
  logic signed [13:0] x_re;  /* sfix14 */
  logic signed [14:0] Radix22ButterflyG1_btf1_re_reg;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_btf1_im_reg;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_btf2_re_reg;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_btf2_im_reg;  /* sfix15 */
  logic signed [13:0] Radix22ButterflyG1_x_re_dly1;  /* sfix14 */
  logic signed [13:0] Radix22ButterflyG1_x_im_dly1;  /* sfix14 */
  logic Radix22ButterflyG1_x_vld_dly1;
  logic signed [13:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  /* sfix14 */
  logic signed [13:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  /* sfix14 */
  logic signed [13:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  /* sfix14 */
  logic signed [13:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  /* sfix14 */
  logic Radix22ButterflyG1_dinXtwdl_vld_dly1;
  logic Radix22ButterflyG1_dinXtwdl_vld_dly2;
  logic signed [14:0] Radix22ButterflyG1_btf1_re_reg_next;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_btf1_im_reg_next;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_btf2_re_reg_next;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_btf2_im_reg_next;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_1;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_2;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_3;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_4;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_5;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_6;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_7;  /* sfix15 */
  logic signed [14:0] Radix22ButterflyG1_8;  /* sfix15 */
  logic signed [13:0] xf_re;  /* sfix14 */
  logic signed [13:0] xf_im;  /* sfix14 */
  logic xf_vld;
  logic signed [13:0] dinXTwdlf_re;  /* sfix14 */
  logic signed [13:0] dinXTwdlf_im;  /* sfix14 */
  logic dinxTwdlf_vld;
  logic signed [13:0] btf1_re;  /* sfix14 */
  logic signed [13:0] btf1_im;  /* sfix14 */
  logic signed [13:0] btf2_re;  /* sfix14 */
  logic signed [13:0] btf2_im;  /* sfix14 */
  logic btf_vld;


  assign din_re = {din_1_1_re_dly[12], din_1_1_re_dly};



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinXTwdl_re <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          dinXTwdl_re <= din_re;
        end
      end
    end



  assign din_im = {din_1_1_im_dly[12], din_1_1_im_dly};



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinXTwdl_im <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          dinXTwdl_im <= din_im;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinXTwdl_1_1_vld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          dinXTwdl_1_1_vld_1 <= din_1_vld_dly;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_1_Enb;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(9),
                              .DataWidth(14)
                              )
                            u_dataMEM_im_0_1 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_im),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_1_Addr),
                                              .dout(x_im)
                                              );

  SimpleDualPortRAM_generic #(.AddrWidth(9),
                              .DataWidth(14)
                              )
                            u_dataMEM_re_0_1 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_re),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_1_Addr),
                                              .dout(x_re)
                                              );

  // Radix22ButterflyG1
  always_ff @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 15'sb000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 15'sb000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 15'sb000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 15'sb000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 14'sb00000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 14'sb00000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 14'sb00000000000000;
        xf_im <= 14'sb00000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 14'sb00000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 14'sb00000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 14'sb00000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 14'sb00000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_1_enb && dinXTwdl_1_1_vld_1;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_1_enb) && dinXTwdl_1_1_vld_1;
  assign Radix22ButterflyG1_1 = {Radix22ButterflyG1_x_re_dly1[13], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_2 = {Radix22ButterflyG1_dinXtwdl_re_dly2[13], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_1 + Radix22ButterflyG1_2;
  assign Radix22ButterflyG1_3 = {Radix22ButterflyG1_x_re_dly1[13], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_4 = {Radix22ButterflyG1_dinXtwdl_re_dly2[13], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_3 - Radix22ButterflyG1_4;
  assign Radix22ButterflyG1_5 = {Radix22ButterflyG1_x_im_dly1[13], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_6 = {Radix22ButterflyG1_dinXtwdl_im_dly2[13], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_5 + Radix22ButterflyG1_6;
  assign Radix22ButterflyG1_7 = {Radix22ButterflyG1_x_im_dly1[13], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_8 = {Radix22ButterflyG1_dinXtwdl_im_dly2[13], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_7 - Radix22ButterflyG1_8;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[13:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[13:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[13:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[13:0];



  SDFCommutator1_block1 u_SDFCOMMUTATOR_1 (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .din_1_vld_dly(din_1_vld_dly),
                                           .xf_re(xf_re),  /* sfix14 */
                                           .xf_im(xf_im),  /* sfix14 */
                                           .xf_vld(xf_vld),
                                           .dinXTwdlf_re(dinXTwdlf_re),  /* sfix14 */
                                           .dinXTwdlf_im(dinXTwdlf_im),  /* sfix14 */
                                           .dinxTwdlf_vld(dinxTwdlf_vld),
                                           .btf1_re(btf1_re),  /* sfix14 */
                                           .btf1_im(btf1_im),  /* sfix14 */
                                           .btf2_re(btf2_re),  /* sfix14 */
                                           .btf2_im(btf2_im),  /* sfix14 */
                                           .btf_vld(btf_vld),
                                           .softReset(softReset),
                                           .wrData_re(wrData_re),  /* sfix14 */
                                           .wrData_im(wrData_im),  /* sfix14 */
                                           .wrAddr(wrAddr),  /* ufix9 */
                                           .wrEnb(wrEnb),
                                           .dout_1_1_re(dout_1_1_re),  /* sfix14 */
                                           .dout_1_1_im(dout_1_1_im),  /* sfix14 */
                                           .dout_1_1_vld(dout_1_1_vld)
                                           );

  assign dinXTwdl_1_1_vld = dinXTwdl_1_1_vld_1;

endmodule  // RADIX22FFT_SDF1_1_block1

