// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\RADIX22FFT_SDF2_4_block.sv
// Created: 2024-03-28 20:55:43
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------


import envelopeModulation_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF2_4_block
// Source Path: envelopeModulation_fixpt/dsphdl.FFT/RADIX22FFT_SDF2_4
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF2_4_block
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] dout_3_1_re  /* sfix16 */,
             input logic signed [15:0] dout_3_1_im  /* sfix16 */,
             input logic dout_3_1_vld,
             input logic [5:0] rd_4_Addr  /* ufix6 */,
             input logic rd_4_Enb,
             input logic proc_4_enb,
             input logic multiply_4_J,
             input logic softReset,
             output logic signed [16:0] dout_4_1_re  /* sfix17 */,
             output logic signed [16:0] dout_4_1_im  /* sfix17 */,
             output logic dout_4_1_vld,
             output logic dinXTwdl_4_1_vld);


  logic signed [16:0] din_re;  /* sfix17 */
  logic signed [16:0] din_im;  /* sfix17 */
  logic btfin_vld;
  logic saveEnb;
  logic dinVld;
  logic x_vld;
  logic x_vld_dly;
  logic signed [16:0] wrData_im;  /* sfix17 */
  logic [5:0] wrAddr;  /* ufix6 */
  logic wrEnb;
  logic signed [16:0] x_im;  /* sfix17 */
  logic signed [16:0] x_im_dly;  /* sfix17 */
  logic signed [16:0] wrData_re;  /* sfix17 */
  logic signed [16:0] x_re;  /* sfix17 */
  logic signed [16:0] x_re_dly;  /* sfix17 */
  logic Radix22ButterflyG2_procEnb_dly;
  logic Radix22ButterflyG2_procEnb_dly1;
  logic Radix22ButterflyG2_procEnb_dly2;
  logic signed [17:0] Radix22ButterflyG2_btf1_re_reg;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_btf1_im_reg;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_btf2_re_reg;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_btf2_im_reg;  /* sfix18 */
  logic signed [16:0] Radix22ButterflyG2_din_re_dly;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_din_im_dly;  /* sfix17 */
  logic Radix22ButterflyG2_din_vld_dly;
  logic signed [16:0] Radix22ButterflyG2_x_re_dly;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_x_im_dly;  /* sfix17 */
  logic Radix22ButterflyG2_x_vld_dly;
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  /* sfix17 */
  logic Radix22ButterflyG2_multiply_J_dly1;
  logic Radix22ButterflyG2_procEnb_dly_next;
  logic Radix22ButterflyG2_procEnb_dly1_next;
  logic Radix22ButterflyG2_procEnb_dly2_next;
  logic signed [17:0] Radix22ButterflyG2_btf1_re_reg_next;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_btf1_im_reg_next;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_btf2_re_reg_next;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_btf2_im_reg_next;  /* sfix18 */
  logic signed [16:0] Radix22ButterflyG2_din_re_dly_next;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_din_im_dly_next;  /* sfix17 */
  logic Radix22ButterflyG2_din_vld_dly_next;
  logic signed [16:0] Radix22ButterflyG2_x_re_dly_next;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_x_im_dly_next;  /* sfix17 */
  logic Radix22ButterflyG2_x_vld_dly_next;
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  /* sfix17 */
  logic signed [16:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  /* sfix17 */
  logic Radix22ButterflyG2_multiply_J_dly1_next;
  logic signed [16:0] xf_re;  /* sfix17 */
  logic signed [16:0] xf_im;  /* sfix17 */
  logic xf_vld;
  logic signed [16:0] dinf_re;  /* sfix17 */
  logic signed [16:0] dinf_im;  /* sfix17 */
  logic dinf_vld;
  logic signed [16:0] btf1_re;  /* sfix17 */
  logic signed [16:0] btf1_im;  /* sfix17 */
  logic signed [16:0] btf2_re;  /* sfix17 */
  logic signed [16:0] btf2_im;  /* sfix17 */
  logic btfout_vld;
  logic signed [17:0] Radix22ButterflyG2_t_0;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_1;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_2;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_3;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_4;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_5;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_6;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_7;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_8;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_9;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_10;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_11;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_12;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_13;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_14;  /* sfix18 */
  logic signed [17:0] Radix22ButterflyG2_t_15;  /* sfix18 */


  assign din_re = {dout_3_1_re[15], dout_3_1_re};



  assign din_im = {dout_3_1_im[15], dout_3_1_im};



  assign btfin_vld = dout_3_1_vld & proc_4_enb;



  assign saveEnb =  ~ btfin_vld;



  assign dinVld = dout_3_1_vld & saveEnb;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_4_Enb;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(6),
                              .DataWidth(17)
                              )
                            u_dataMEM_im_0_4 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_im),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_4_Addr),
                                              .dout(x_im)
                                              );

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        x_im_dly <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(6),
                              .DataWidth(17)
                              )
                            u_dataMEM_re_0_4 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_re),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_4_Addr),
                                              .dout(x_re)
                                              );

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_re_dly <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always_ff @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 18'sb000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 18'sb000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 18'sb000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 18'sb000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 17'sb00000000000000000;
        Radix22ButterflyG2_din_im_dly <= 17'sb00000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 17'sb00000000000000000;
        Radix22ButterflyG2_x_im_dly <= 17'sb00000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 17'sb00000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 17'sb00000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_vld,
       dinVld, din_im, din_re, multiply_4_J, x_im_dly, x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_t_0 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_1 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_2 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_3 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_4 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_5 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_6 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_7 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_8 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_9 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_10 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_11 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_12 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_13 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_14 = 18'sb000000000000000000;
    Radix22ButterflyG2_t_15 = 18'sb000000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_t_0 = {x_re_dly[16], x_re_dly};
      Radix22ButterflyG2_t_1 = {Radix22ButterflyG2_dinXTwdl_im_dly2[16], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_t_0 + Radix22ButterflyG2_t_1;
      Radix22ButterflyG2_t_2 = {x_re_dly[16], x_re_dly};
      Radix22ButterflyG2_t_3 = {Radix22ButterflyG2_dinXTwdl_im_dly2[16], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_t_2 - Radix22ButterflyG2_t_3;
      Radix22ButterflyG2_t_4 = {x_im_dly[16], x_im_dly};
      Radix22ButterflyG2_t_5 = {Radix22ButterflyG2_dinXTwdl_re_dly2[16], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_t_4 + Radix22ButterflyG2_t_5;
      Radix22ButterflyG2_t_6 = {x_im_dly[16], x_im_dly};
      Radix22ButterflyG2_t_7 = {Radix22ButterflyG2_dinXTwdl_re_dly2[16], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_t_6 - Radix22ButterflyG2_t_7;
    end
    else begin
      Radix22ButterflyG2_t_8 = {x_re_dly[16], x_re_dly};
      Radix22ButterflyG2_t_9 = {Radix22ButterflyG2_dinXTwdl_re_dly2[16], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_t_8 + Radix22ButterflyG2_t_9;
      Radix22ButterflyG2_t_10 = {x_re_dly[16], x_re_dly};
      Radix22ButterflyG2_t_11 = {Radix22ButterflyG2_dinXTwdl_re_dly2[16], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_t_10 - Radix22ButterflyG2_t_11;
      Radix22ButterflyG2_t_12 = {x_im_dly[16], x_im_dly};
      Radix22ButterflyG2_t_13 = {Radix22ButterflyG2_dinXTwdl_im_dly2[16], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_t_12 + Radix22ButterflyG2_t_13;
      Radix22ButterflyG2_t_14 = {x_im_dly[16], x_im_dly};
      Radix22ButterflyG2_t_15 = {Radix22ButterflyG2_dinXTwdl_im_dly2[16], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_t_14 - Radix22ButterflyG2_t_15;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = din_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = din_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_4_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[16:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[16:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[16:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[16:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  SDFCommutator4_block u_SDFCOMMUTATOR_4 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .dout_3_1_vld(dout_3_1_vld),
                                          .xf_re(xf_re),  /* sfix17 */
                                          .xf_im(xf_im),  /* sfix17 */
                                          .xf_vld(xf_vld),
                                          .dinf_re(dinf_re),  /* sfix17 */
                                          .dinf_im(dinf_im),  /* sfix17 */
                                          .dinf_vld(dinf_vld),
                                          .btf1_re(btf1_re),  /* sfix17 */
                                          .btf1_im(btf1_im),  /* sfix17 */
                                          .btf2_re(btf2_re),  /* sfix17 */
                                          .btf2_im(btf2_im),  /* sfix17 */
                                          .btfout_vld(btfout_vld),
                                          .softReset(softReset),
                                          .wrData_re(wrData_re),  /* sfix17 */
                                          .wrData_im(wrData_im),  /* sfix17 */
                                          .wrAddr(wrAddr),  /* ufix6 */
                                          .wrEnb(wrEnb),
                                          .dout_4_1_re(dout_4_1_re),  /* sfix17 */
                                          .dout_4_1_im(dout_4_1_im),  /* sfix17 */
                                          .dout_4_1_vld(dout_4_1_vld)
                                          );

  assign dinXTwdl_4_1_vld = btfin_vld;

endmodule  // RADIX22FFT_SDF2_4_block

