// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\RADIX22FFT_CTRL1_10_block1.sv
// Created: 2024-03-28 20:55:43
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------


import envelopeModulation_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: RADIX22FFT_CTRL1_10_block1
// Source Path: envelopeModulation_fixpt/dsphdl.FFT/RADIX22FFT_CTRL1_10
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_CTRL1_10_block1
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic dout_9_1_vld,
             input logic dinXTwdl_10_1_vld,
             input logic softReset,
             output logic rd_10_Addr,
             output logic rd_10_Enb,
             output logic proc_10_enb,
             output logic multiply_10_J);


  logic [1:0] SDFController_wrState;  /* ufix2 */
  logic [1:0] SDFController_rdState;  /* ufix2 */
  logic SDFController_rdAddr_reg;  /* ufix1 */
  logic [1:0] SDFController_multjState;  /* ufix2 */
  logic [1:0] SDFController_wrState_next;  /* ufix2 */
  logic [1:0] SDFController_rdState_next;  /* ufix2 */
  logic SDFController_rdAddr_reg_next;  /* ufix1 */
  logic [1:0] SDFController_multjState_next;  /* ufix2 */
  logic rd_10_Addr_1;
  logic rd_10_Enb_1;
  logic proc_10_enb_1;
  logic multiply_10_J_1;


  // SDFController
  always_ff @(posedge clk or posedge reset)
    begin : SDFController_process
      if (reset == 1'b1) begin
        SDFController_rdAddr_reg <= 1'b0;
        SDFController_wrState <= 2'b00;
        SDFController_rdState <= 2'b00;
        SDFController_multjState <= 2'b00;
      end
      else begin
        if (enb) begin
          SDFController_wrState <= SDFController_wrState_next;
          SDFController_rdState <= SDFController_rdState_next;
          SDFController_rdAddr_reg <= SDFController_rdAddr_reg_next;
          SDFController_multjState <= SDFController_multjState_next;
        end
      end
    end

  always @(SDFController_multjState, SDFController_rdAddr_reg, SDFController_rdState,
       SDFController_wrState, dinXTwdl_10_1_vld, dout_9_1_vld) begin
    SDFController_rdState_next = SDFController_rdState;
    SDFController_rdAddr_reg_next = SDFController_rdAddr_reg;
    SDFController_multjState_next = SDFController_multjState;
    case ( SDFController_multjState)
      2'b00 :
        begin
          SDFController_multjState_next = 2'b00;
          multiply_10_J_1 = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          multiply_10_J_1 = 1'b0;
          if (SDFController_rdState == 2'b00) begin
            SDFController_multjState_next = 2'b10;
          end
        end
      2'b10 :
        begin
          multiply_10_J_1 = 1'b0;
          SDFController_multjState_next = 2'b11;
        end
      2'b11 :
        begin
          multiply_10_J_1 = 1'b1;
          SDFController_multjState_next = 2'b00;
        end
      default :
        begin
          SDFController_multjState_next = 2'b00;
          multiply_10_J_1 = 1'b0;
        end
    endcase
    case ( SDFController_rdState)
      2'b00 :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 1'b0;
          rd_10_Enb_1 = 1'b0;
          if ((SDFController_wrState == 2'b11) && dout_9_1_vld) begin
            SDFController_rdState_next = 2'b01;
            rd_10_Enb_1 = dinXTwdl_10_1_vld;
          end
        end
      2'b01 :
        begin
          rd_10_Enb_1 = dinXTwdl_10_1_vld;
          if (dinXTwdl_10_1_vld) begin
            SDFController_rdState_next = 2'b00;
          end
        end
      default :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 1'b0;
          rd_10_Enb_1 = 1'b0;
        end
    endcase
    case ( SDFController_wrState)
      2'b00 :
        begin
          SDFController_wrState_next = 2'b00;
          proc_10_enb_1 = 1'b0;
          if (dout_9_1_vld) begin
            SDFController_wrState_next = 2'b11;
          end
        end
      2'b11 :
        begin
          SDFController_wrState_next = 2'b11;
          proc_10_enb_1 = 1'b0;
          if (dout_9_1_vld) begin
            SDFController_wrState_next = 2'b10;
            proc_10_enb_1 = 1'b1;
          end
        end
      2'b10 :
        begin
          proc_10_enb_1 = 1'b0;
          SDFController_wrState_next = 2'b10;
          if (dout_9_1_vld) begin
            SDFController_wrState_next = 2'b11;
          end
        end
      default :
        begin
          SDFController_wrState_next = 2'b00;
          proc_10_enb_1 = 1'b0;
        end
    endcase
    rd_10_Addr_1 = SDFController_rdAddr_reg;
  end



  assign rd_10_Addr = rd_10_Addr_1;

  assign rd_10_Enb = rd_10_Enb_1;

  assign proc_10_enb = proc_10_enb_1;

  assign multiply_10_J = multiply_10_J_1;

endmodule  // RADIX22FFT_CTRL1_10_block1

