// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\SDFCommutator7_block.sv
// Created: 2024-03-28 20:55:43
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------


import envelopeModulation_fixpt_pkg::* ;

// -------------------------------------------------------------
// 
// Module: SDFCommutator7_block
// Source Path: envelopeModulation_fixpt/dsphdl.FFT/RADIX22FFT_SDF1_7/SDFCommutator7
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SDFCommutator7_block
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic din_7_vld_dly,
             input logic signed [19:0] xf_re  /* sfix20 */,
             input logic signed [19:0] xf_im  /* sfix20 */,
             input logic xf_vld,
             input logic signed [19:0] dinXTwdlf_re  /* sfix20 */,
             input logic signed [19:0] dinXTwdlf_im  /* sfix20 */,
             input logic dinxTwdlf_vld,
             input logic signed [19:0] btf1_re  /* sfix20 */,
             input logic signed [19:0] btf1_im  /* sfix20 */,
             input logic signed [19:0] btf2_re  /* sfix20 */,
             input logic signed [19:0] btf2_im  /* sfix20 */,
             input logic btf_vld,
             input logic softReset,
             output logic signed [19:0] wrData_re  /* sfix20 */,
             output logic signed [19:0] wrData_im  /* sfix20 */,
             output logic [2:0] wrAddr  /* ufix3 */,
             output logic wrEnb,
             output logic signed [19:0] dout_7_1_re  /* sfix20 */,
             output logic signed [19:0] dout_7_1_im  /* sfix20 */,
             output logic dout_7_1_vld);


  logic signed [19:0] SDFCummutator_out_re;  /* sfix20 */
  logic signed [19:0] SDFCummutator_out_im;  /* sfix20 */
  logic SDFCummutator_out_vld;
  logic [2:0] SDFCummutator_wrAddr_reg;  /* ufix3 */
  logic [2:0] SDFCummutator_wrState;  /* ufix3 */
  logic signed [19:0] SDFCummutator_wrData_re_reg;  /* sfix20 */
  logic signed [19:0] SDFCummutator_wrData_im_reg;  /* sfix20 */
  logic SDFCummutator_wrEnb_reg;
  logic signed [19:0] SDFCummutator_wrXData_re_reg;  /* sfix20 */
  logic signed [19:0] SDFCummutator_wrXData_im_reg;  /* sfix20 */
  logic [2:0] SDFCummutator_xWrAddr;  /* ufix3 */
  logic SDFCummutator_wrxEnb_reg;
  logic [2:0] SDFCummutator_xRdAddr;  /* ufix3 */
  logic [2:0] SDFCummutator_XState;  /* ufix3 */
  logic SDFCummutator_xX_vld_reg;
  logic signed [19:0] SDFCummutator_out_re_next;  /* sfix20 */
  logic signed [19:0] SDFCummutator_out_im_next;  /* sfix20 */
  logic SDFCummutator_out_vld_next;
  logic [2:0] SDFCummutator_wrAddr_reg_next;  /* ufix3 */
  logic [2:0] SDFCummutator_wrState_next;  /* ufix3 */
  logic signed [19:0] SDFCummutator_wrData_re_reg_next;  /* sfix20 */
  logic signed [19:0] SDFCummutator_wrData_im_reg_next;  /* sfix20 */
  logic SDFCummutator_wrEnb_reg_next;
  logic signed [19:0] SDFCummutator_wrXData_re_reg_next;  /* sfix20 */
  logic signed [19:0] SDFCummutator_wrXData_im_reg_next;  /* sfix20 */
  logic [2:0] SDFCummutator_xWrAddr_next;  /* ufix3 */
  logic SDFCummutator_wrxEnb_reg_next;
  logic [2:0] SDFCummutator_xRdAddr_next;  /* ufix3 */
  logic [2:0] SDFCummutator_XState_next;  /* ufix3 */
  logic SDFCummutator_xX_vld_reg_next;
  logic signed [19:0] wrData_re_1;  /* sfix20 */
  logic signed [19:0] wrData_im_1;  /* sfix20 */
  logic [2:0] wrAddr_1;  /* ufix3 */
  logic wrEnb_1;
  logic signed [19:0] xData_re;  /* sfix20 */
  logic signed [19:0] xData_im;  /* sfix20 */
  logic [2:0] wrXAddr;  /* ufix3 */
  logic wrXEnb;
  logic [2:0] rdXAddr;  /* ufix3 */
  logic xX_vld;
  logic signed [19:0] dout0_re;  /* sfix20 */
  logic signed [19:0] dout0_im;  /* sfix20 */
  logic dout0_vld;
  logic signed [19:0] xX_re;  /* sfix20 */
  logic signed [19:0] xX_im;  /* sfix20 */
  logic signed [19:0] SDFOutmux_btf2Pipe_re;  /* sfix20 */
  logic signed [19:0] SDFOutmux_btf2Pipe_im;  /* sfix20 */
  logic SDFOutmux_btfPipe_vld;
  logic signed [19:0] SDFOutmux_btf2Pipe_re_next;  /* sfix20 */
  logic signed [19:0] SDFOutmux_btf2Pipe_im_next;  /* sfix20 */
  logic SDFOutmux_btfPipe_vld_next;
  logic signed [19:0] dout_7_1_re_1;  /* sfix20 */
  logic signed [19:0] dout_7_1_im_1;  /* sfix20 */
  logic dout_7_1_vld_1;


  // SDFCummutator
  always_ff @(posedge clk or posedge reset)
    begin : SDFCummutator_process
      if (reset == 1'b1) begin
        SDFCummutator_out_re <= 20'sb00000000000000000000;
        SDFCummutator_out_im <= 20'sb00000000000000000000;
        SDFCummutator_wrData_re_reg <= 20'sb00000000000000000000;
        SDFCummutator_wrData_im_reg <= 20'sb00000000000000000000;
        SDFCummutator_wrEnb_reg <= 1'b0;
        SDFCummutator_out_vld <= 1'b0;
        SDFCummutator_wrState <= 3'b000;
        SDFCummutator_wrAddr_reg <= 3'b000;
        SDFCummutator_wrXData_re_reg <= 20'sb00000000000000000000;
        SDFCummutator_wrXData_im_reg <= 20'sb00000000000000000000;
        SDFCummutator_xWrAddr <= 3'b000;
        SDFCummutator_wrxEnb_reg <= 1'b0;
        SDFCummutator_xRdAddr <= 3'b000;
        SDFCummutator_XState <= 3'b000;
        SDFCummutator_xX_vld_reg <= 1'b0;
      end
      else begin
        if (enb) begin
          SDFCummutator_out_re <= SDFCummutator_out_re_next;
          SDFCummutator_out_im <= SDFCummutator_out_im_next;
          SDFCummutator_out_vld <= SDFCummutator_out_vld_next;
          SDFCummutator_wrAddr_reg <= SDFCummutator_wrAddr_reg_next;
          SDFCummutator_wrState <= SDFCummutator_wrState_next;
          SDFCummutator_wrData_re_reg <= SDFCummutator_wrData_re_reg_next;
          SDFCummutator_wrData_im_reg <= SDFCummutator_wrData_im_reg_next;
          SDFCummutator_wrEnb_reg <= SDFCummutator_wrEnb_reg_next;
          SDFCummutator_wrXData_re_reg <= SDFCummutator_wrXData_re_reg_next;
          SDFCummutator_wrXData_im_reg <= SDFCummutator_wrXData_im_reg_next;
          SDFCummutator_xWrAddr <= SDFCummutator_xWrAddr_next;
          SDFCummutator_wrxEnb_reg <= SDFCummutator_wrxEnb_reg_next;
          SDFCummutator_xRdAddr <= SDFCummutator_xRdAddr_next;
          SDFCummutator_XState <= SDFCummutator_XState_next;
          SDFCummutator_xX_vld_reg <= SDFCummutator_xX_vld_reg_next;
        end
      end
    end

  always @(SDFCummutator_XState, SDFCummutator_out_im, SDFCummutator_out_re,
       SDFCummutator_out_vld, SDFCummutator_wrAddr_reg,
       SDFCummutator_wrData_im_reg, SDFCummutator_wrData_re_reg,
       SDFCummutator_wrEnb_reg, SDFCummutator_wrState,
       SDFCummutator_wrXData_im_reg, SDFCummutator_wrXData_re_reg,
       SDFCummutator_wrxEnb_reg, SDFCummutator_xRdAddr, SDFCummutator_xWrAddr,
       SDFCummutator_xX_vld_reg, btf1_im, btf1_re, btf2_im, btf2_re, btf_vld,
       dinXTwdlf_im, dinXTwdlf_re, din_7_vld_dly, dinxTwdlf_vld) begin
    SDFCummutator_wrAddr_reg_next = SDFCummutator_wrAddr_reg;
    SDFCummutator_wrXData_re_reg_next = SDFCummutator_wrXData_re_reg;
    SDFCummutator_wrXData_im_reg_next = SDFCummutator_wrXData_im_reg;
    SDFCummutator_xWrAddr_next = SDFCummutator_xWrAddr;
    SDFCummutator_wrxEnb_reg_next = SDFCummutator_wrxEnb_reg;
    SDFCummutator_xRdAddr_next = SDFCummutator_xRdAddr;
    SDFCummutator_XState_next = SDFCummutator_XState;
    SDFCummutator_xX_vld_reg_next = SDFCummutator_xX_vld_reg;
    case ( SDFCummutator_XState)
      3'b000 :
        begin
          SDFCummutator_wrXData_re_reg_next = 20'sb00000000000000000000;
          SDFCummutator_wrXData_im_reg_next = 20'sb00000000000000000000;
          SDFCummutator_xWrAddr_next = 3'b000;
          SDFCummutator_xRdAddr_next = 3'b000;
          SDFCummutator_wrxEnb_reg_next = 1'b0;
          SDFCummutator_xX_vld_reg_next = 1'b0;
          if (btf_vld) begin
            SDFCummutator_xWrAddr_next = 3'b000;
            SDFCummutator_wrxEnb_reg_next = 1'b1;
            SDFCummutator_wrXData_re_reg_next = btf2_re;
            SDFCummutator_wrXData_im_reg_next = btf2_im;
            SDFCummutator_XState_next = 3'b010;
          end
        end
      3'b010 :
        begin
          SDFCummutator_wrXData_re_reg_next = btf2_re;
          SDFCummutator_wrXData_im_reg_next = btf2_im;
          SDFCummutator_xX_vld_reg_next = 1'b0;
          if (SDFCummutator_xWrAddr == 3'b111) begin
            SDFCummutator_wrxEnb_reg_next = 1'b0;
            SDFCummutator_XState_next = 3'b100;
            SDFCummutator_xX_vld_reg_next = 1'b1;
            SDFCummutator_xRdAddr_next = 3'b001;
            SDFCummutator_xWrAddr_next = 3'b000;
          end
          else if (btf_vld) begin
            SDFCummutator_XState_next = 3'b010;
            SDFCummutator_wrxEnb_reg_next = 1'b1;
            SDFCummutator_xWrAddr_next = SDFCummutator_xWrAddr + 3'b001;
          end
          else begin
            SDFCummutator_XState_next = 3'b010;
            SDFCummutator_wrxEnb_reg_next = 1'b0;
          end
        end
      3'b100 :
        begin
          if (SDFCummutator_xRdAddr == 3'b111) begin
            SDFCummutator_xX_vld_reg_next = 1'b1;
            SDFCummutator_xWrAddr_next = 3'b000;
            SDFCummutator_xRdAddr_next = 3'b000;
            SDFCummutator_wrXData_re_reg_next = btf2_re;
            SDFCummutator_wrXData_im_reg_next = btf2_im;
            if (btf_vld) begin
              SDFCummutator_wrxEnb_reg_next = 1'b1;
              SDFCummutator_XState_next = 3'b010;
            end
            else begin
              SDFCummutator_wrxEnb_reg_next = 1'b0;
              SDFCummutator_XState_next = 3'b000;
            end
          end
          else begin
            SDFCummutator_xRdAddr_next = SDFCummutator_xRdAddr + 3'b001;
          end
        end
      default :
        begin
          SDFCummutator_wrXData_re_reg_next = 20'sb00000000000000000000;
          SDFCummutator_wrXData_im_reg_next = 20'sb00000000000000000000;
          SDFCummutator_xWrAddr_next = 3'b000;
          SDFCummutator_xRdAddr_next = 3'b000;
          SDFCummutator_wrxEnb_reg_next = 1'b0;
          SDFCummutator_XState_next = 3'b000;
        end
    endcase
    SDFCummutator_out_re_next = btf1_re;
    SDFCummutator_out_im_next = btf1_im;
    SDFCummutator_out_vld_next = btf_vld;
    case ( SDFCummutator_wrState)
      3'b000 :
        begin
          SDFCummutator_wrState_next = 3'b000;
          SDFCummutator_wrAddr_reg_next = 3'b000;
          SDFCummutator_wrData_re_reg_next = dinXTwdlf_re;
          SDFCummutator_wrData_im_reg_next = dinXTwdlf_im;
          SDFCummutator_wrEnb_reg_next = 1'b0;
          if (dinxTwdlf_vld) begin
            SDFCummutator_wrState_next = 3'b001;
            SDFCummutator_wrAddr_reg_next = 3'b000;
            SDFCummutator_wrEnb_reg_next = 1'b1;
          end
        end
      3'b001 :
        begin
          SDFCummutator_wrState_next = 3'b001;
          SDFCummutator_wrEnb_reg_next = 1'b0;
          SDFCummutator_wrData_re_reg_next = dinXTwdlf_re;
          SDFCummutator_wrData_im_reg_next = dinXTwdlf_im;
          if (SDFCummutator_wrAddr_reg == 3'b111) begin
            SDFCummutator_wrState_next = 3'b011;
          end
          if (dinxTwdlf_vld) begin
            if (SDFCummutator_wrAddr_reg == 3'b111) begin
              SDFCummutator_wrAddr_reg_next = 3'b000;
              SDFCummutator_wrEnb_reg_next = 1'b0;
            end
            else begin
              SDFCummutator_wrAddr_reg_next = SDFCummutator_wrAddr_reg + 3'b001;
              SDFCummutator_wrEnb_reg_next = 1'b1;
            end
          end
        end
      3'b011 :
        begin
          SDFCummutator_wrState_next = 3'b011;
          SDFCummutator_wrEnb_reg_next = 1'b0;
          SDFCummutator_wrData_re_reg_next = dinXTwdlf_re;
          SDFCummutator_wrData_im_reg_next = dinXTwdlf_im;
          if (SDFCummutator_wrAddr_reg == 3'b111) begin
            SDFCummutator_wrAddr_reg_next = 3'b000;
            if (dinxTwdlf_vld) begin
              SDFCummutator_wrState_next = 3'b001;
              SDFCummutator_wrEnb_reg_next = 1'b1;
            end
            else begin
              SDFCummutator_wrState_next = 3'b000;
              SDFCummutator_wrEnb_reg_next = 1'b0;
            end
          end
          else if (din_7_vld_dly) begin
            SDFCummutator_wrState_next = 3'b011;
            SDFCummutator_wrAddr_reg_next = SDFCummutator_wrAddr_reg + 3'b001;
          end
        end
      default :
        begin
          SDFCummutator_wrState_next = 3'b000;
          SDFCummutator_wrAddr_reg_next = 3'b000;
          SDFCummutator_wrEnb_reg_next = 1'b0;
          SDFCummutator_wrData_re_reg_next = dinXTwdlf_re;
          SDFCummutator_wrData_im_reg_next = dinXTwdlf_im;
        end
    endcase
    wrData_re_1 = SDFCummutator_wrData_re_reg;
    wrData_im_1 = SDFCummutator_wrData_im_reg;
    wrAddr_1 = SDFCummutator_wrAddr_reg;
    wrEnb_1 = SDFCummutator_wrEnb_reg;
    xData_re = SDFCummutator_wrXData_re_reg;
    xData_im = SDFCummutator_wrXData_im_reg;
    wrXAddr = SDFCummutator_xWrAddr;
    wrXEnb = SDFCummutator_wrxEnb_reg;
    rdXAddr = SDFCummutator_xRdAddr;
    xX_vld = SDFCummutator_xX_vld_reg;
    dout0_re = SDFCummutator_out_re;
    dout0_im = SDFCummutator_out_im;
    dout0_vld = SDFCummutator_out_vld;
  end



  SimpleDualPortRAM_generic #(.AddrWidth(3),
                              .DataWidth(20)
                              )
                            u_dataXMEM_re_0_7 (.clk(clk),
                                               .enb(enb),
                                               .wr_din(xData_re),
                                               .wr_addr(wrXAddr),
                                               .wr_en(wrXEnb),
                                               .rd_addr(rdXAddr),
                                               .dout(xX_re)
                                               );

  SimpleDualPortRAM_generic #(.AddrWidth(3),
                              .DataWidth(20)
                              )
                            u_dataXMEM_im_0_7 (.clk(clk),
                                               .enb(enb),
                                               .wr_din(xData_im),
                                               .wr_addr(wrXAddr),
                                               .wr_en(wrXEnb),
                                               .rd_addr(rdXAddr),
                                               .dout(xX_im)
                                               );

  // SDFOutmux
  always_ff @(posedge clk or posedge reset)
    begin : SDFOutmux_process
      if (reset == 1'b1) begin
        SDFOutmux_btf2Pipe_re <= 20'sb00000000000000000000;
        SDFOutmux_btf2Pipe_im <= 20'sb00000000000000000000;
        SDFOutmux_btfPipe_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          SDFOutmux_btf2Pipe_re <= SDFOutmux_btf2Pipe_re_next;
          SDFOutmux_btf2Pipe_im <= SDFOutmux_btf2Pipe_im_next;
          SDFOutmux_btfPipe_vld <= SDFOutmux_btfPipe_vld_next;
        end
      end
    end

  always @(SDFOutmux_btf2Pipe_im, SDFOutmux_btf2Pipe_re, SDFOutmux_btfPipe_vld, dout0_im,
       dout0_re, dout0_vld, xX_im, xX_re, xX_vld) begin
    SDFOutmux_btf2Pipe_re_next = SDFOutmux_btf2Pipe_re;
    SDFOutmux_btf2Pipe_im_next = SDFOutmux_btf2Pipe_im;
    if (dout0_vld) begin
      SDFOutmux_btf2Pipe_re_next = dout0_re;
      SDFOutmux_btf2Pipe_im_next = dout0_im;
      SDFOutmux_btfPipe_vld_next = 1'b1;
    end
    else if (xX_vld) begin
      SDFOutmux_btf2Pipe_re_next = xX_re;
      SDFOutmux_btf2Pipe_im_next = xX_im;
      SDFOutmux_btfPipe_vld_next = 1'b1;
    end
    else begin
      SDFOutmux_btfPipe_vld_next = 1'b0;
    end
    dout_7_1_re_1 = SDFOutmux_btf2Pipe_re;
    dout_7_1_im_1 = SDFOutmux_btf2Pipe_im;
    dout_7_1_vld_1 = SDFOutmux_btfPipe_vld;
  end



  assign wrData_re = wrData_re_1;

  assign wrData_im = wrData_im_1;

  assign wrAddr = wrAddr_1;

  assign wrEnb = wrEnb_1;

  assign dout_7_1_re = dout_7_1_re_1;

  assign dout_7_1_im = dout_7_1_im_1;

  assign dout_7_1_vld = dout_7_1_vld_1;

endmodule  // SDFCommutator7_block

