// -------------------------------------------------------------
// 
// File Name: C:\Users\Hassa\Documents\GitHub\vocoder\MATLAB\MATLAB_CodeGen\codegen\envelopeModulation\hdlsrc\SimpleDualPortRAM_generic.sv
// Created: 2024-03-28 20:55:43
// 
// Generated by MATLAB 23.2, MATLAB Coder 23.2 and HDL Coder 23.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SimpleDualPortRAM_generic
// Source Path: envelopeModulation_fixpt/dsphdl.IFFT/RADIX22FFT_SDF1_1/SimpleDualPortRAM_generic
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SimpleDualPortRAM_generic
          #(  parameter int AddrWidth  = 1,
              parameter int DataWidth  = 1)
          (  input logic clk,
             input logic enb,
             input logic [DataWidth - 1:0] wr_din  /* parameterized width */,
             input logic [AddrWidth - 1:0] wr_addr  /* parameterized width */,
             input logic wr_en  /* ufix1 */,
             input logic [AddrWidth - 1:0] rd_addr  /* parameterized width */,
             output logic [DataWidth - 1:0] dout  /* parameterized width */);


  reg  [DataWidth - 1:0] ram [2**AddrWidth - 1:0];
  reg  [DataWidth - 1:0] data_int;
  integer i;

  initial begin
    for (i=0; i<=2**AddrWidth - 1; i=i+1) begin
      ram[i] = 0;
    end
    data_int = 0;
  end


  always @(posedge clk)
    begin : SimpleDualPortRAM_generic_process
      if (enb == 1'b1) begin
        if (wr_en == 1'b1) begin
          ram[wr_addr] <= wr_din;
        end
        data_int <= ram[rd_addr];
      end
    end

  assign dout = data_int;

endmodule  // SimpleDualPortRAM_generic

